### ISSUE TITLE
[Suggestion] Small animal trap

### ISSUE THREAD

**Issue by Yamor123** [Ekkelus/ECO-Realism#1]
It should be possible to make a trap similar to the fish trap for trapping small animal like hares, turkeys or foxes

**Comment by Ekkelus** [comment]
We have to restrict the usage to pro Hunters only.

**Comment by Yamor123** [comment]
As i said, i'm able to limit authorization so that only people with the right skill and normal authorization are able to interact with the trap (also no access via linked inventories). There are only 2 problems (that i know of):
1. (somewhat neglectable) changes are not made immediatly if you're not accessing the trap directly, may take a relog (or an direct access attempt) after unlearning the skill to lose access via linked inventory
2. traps cant be picked up without having the skills needed to use it

I couldn't really fix problem 2 but i was able to make it less relevant by also making it impossible to place those traps without having the proper Skilllevel
