### ISSUE TITLE
Migration to 7.3

### ISSUE THREAD

**Issue by Yamor123** [Ekkelus/ECO-Realism#12]
7.3 isnt out yet but probably will be in the next few days.
I tried running our modpack on the staging branch and yeah, it obviously did not work..
they changed torch to a tool item, wich was easy to fix. But the new localization support will be a lot of work... we'll hav to change many (but not all) simple strings from `"String"` to `Localizer.Do("String")`... and that wont be to easy as there's no easy way to find and replace those strings directly. Right now thats like 50-60 files to change more or less manually but i guess those will be more in the official 7.3 release. I guess we'll have to wait and see then.

**Comment by Ekkelus** [comment]
Should be done for now, but we'll probably have to check files again when 7.3.0 is released.
