### ISSUE TITLE
Adding more Efficiency levels?

### ISSUE THREAD

**Issue by Yamor123** [Ekkelus/ECO-Realism#5]
Just a thought but maybe we could add higher efficiency levels than 5 so its still possible to get more than 50% efficiency but make those higher levels extremely expensive (100+ SP). Also, i could check if its possible to add Material Costs for those high tier Efficiencys (maybe make it use some special token item that people get handed out 1 each, so they can actually only push 1 efficiency skill to a higher level than 5).

Not sure about that whole idea, just came to my mind earlier.

**Comment by Ekkelus** [comment]
Interesting idea, might be something for next release.

**Comment by Ekkelus** [comment]
**Something to think about:**
What's stopping people from handing out those items?
