### ISSUE TITLE
Increasing overall pollution

### ISSUE THREAD

**Issue by Yamor123** [Ekkelus/ECO-Realism#8]
I think its generally to hard to pollute the planet to a point where it even matters.

While browsing trough the files i noticed that the pollution rates should be easy to change. its also possible to spread ground pollution through crafting stations/pipes.
Its also not to hard to add pollution spreading to stations wich doesn't pollute yet i guess. I'll have a look at it.

**Comment by Ekkelus** [comment]
Please do but let's not make it too difficult :)

**Comment by Yamor123** [comment]
https://docs.google.com/spreadsheets/d/1OEk2k1xjjlIz7TiMlT4mMACKaxZORuM9M1RwgJFiE-g/

maybe double powered cart and Blast furnace, and increase Refinery to 1 (4x)?

adding new polluters can wait i guess

**Comment by Ekkelus** [comment]
Looks like this is fixed already but not closed :)
